version: '3.9'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_social
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/app_social
      JWT_SECRET: supersecret
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  pgdata:
